spring:
  datasource:
    oracle:
      url: jdbc:oracle:thin:@localhost:1521/oracle
      username: system
      password: jqk950914
      driver-class-name: oracle.jdbc.OracleDriver
    postgres:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: jqk950914
      driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
server:
  port: 8080